# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build the project and run tests
        run: mvn --batch-mode resources:resources > /tmp/maven.log
      - name: List the files in the target dir. We should have foo.txt and 中文名称.txt
        run: |
          files=$(ls target/classes | wc -l)
          if [ "$files" -lt 2 ]; then exit $files; fi
